import emen2.globalns
g = emen2.globalns.GlobalNamespace()
import bsddb3

USETXN = True
RECOVER = False

# Berkeley DB Config flags
ENVOPENFLAGS = bsddb3.db.DB_CREATE | bsddb3.db.DB_THREAD | bsddb3.db.DB_INIT_MPOOL | bsddb3.db.DB_REGISTER
DBOPENFLAGS = bsddb3.db.DB_THREAD | bsddb3.db.DB_CREATE  | bsddb3.db.DB_MULTIVERSION
RMWFLAGS = 0


TXNFLAGS = bsddb3.db.DB_TXN_SNAPSHOT
ENVTXNFLAGS = bsddb3.db.DB_INIT_TXN | bsddb3.db.DB_INIT_LOCK |  bsddb3.db.DB_INIT_LOG | bsddb3.db.DB_TXN_SNAPSHOT
RECOVERFLAGS = bsddb3.db.DB_RECOVER


if USETXN:
	ENVOPENFLAGS |= ENVTXNFLAGS | TXNFLAGS
	#DBOPENFLAGS |= bsddb3.db.DB_AUTO_COMMIT | TXNFLAGS
	RMWFLAGS = bsddb3.db.DB_RMW

if RECOVER:
	ENVOPENFLAGS |= RECOVERFLAGS

g.USETXN = USETXN
g.RECOVER = RECOVER
g.ENVOPENFLAGS=ENVOPENFLAGS
g.DBOPENFLAGS=DBOPENFLAGS
g.RMWFLAGS=RMWFLAGS
g.TXNFLAGS=TXNFLAGS
g.RECOVERFLAGS=RECOVERFLAGS
