#!/bin/sh
#
#  Startup script for a Twisted service.
#
#  description: Start-up script for the Twisted service "emen2".

# 1. Get database environment, EMEN2DBHOME, and extensions to load, EMEN2EXTS
# 2. Find Python interpreter.
# 3. Find twistd.py


##### Configuration #####

# Database environment
EMEN2DBHOME=/Users/irees/data/db.ncmi

# Extensions to load
EMEN2EXTS=default,em,eman2,site

# User account to use
EMEN2USER=irees

# EMAN2 Python environment to use
EMAN2DIR=/Users/irees/EMAN2
PYTHON=${EMAN2DIR}/Python/bin/python

##### Init script #####

pidfile=$rundir/applog/emen2.pid
logfile=$rundir/applog/emen2.log
PATH=${EMAN2DIR}/Python/bin:/usr/bin:/bin:/usr/sbin:/sbin

case "$1" in
	start)
		echo "Starting emen2: twistd"
		twistd \
			--pidfile=$pidfile \
			--logfile=$logfile \
			--rundir=$EMEN2DBHOME \
			emen2 -h $EMEN2DBHOME -e ${EMEN2EXTS}
		;;

	stop)
		if [ -f $pidfile ] 
		then
			echo "Stopping emen2: twistd"
			kill `cat "${pidfile}"`
		fi
		;;

	restart)
		"${0}" stop
		"${0}" start
		;;

    *)
		echo "Usage: ${0} {start|stop|restart|}" >&2
		exit 1
		;;
esac

exit 0